### PR TITLE
Use rtd for docs

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by yuanqing-wang** [comment]
@kntkb @mikemhenry the build doc is still failing, is it supposed to be fixed in this PR?

**Comment by yuanqing-wang** [comment]
@mikemhenry @kntkb oh nvm I see that we just need to disable the previous build docs GA

**Comment by ijpulidos** [comment]
Yeah, this one should be ready to go https://espaloma--167.org.readthedocs.build/en/167/ 

Anybody opposing merging this as it is now?

**Comment by yuanqing-wang** [comment]
let's merge once we can disable "Build Doc / docs (push)" GA

**Comment by mikemhenry** [comment]
Sorry! I was just about done with this PR and got distracted, I will clean it up now that it is building!

**Comment by mikemhenry** [comment]
Okay auto merge should take care of this, I will keep an eye on it

**Review by ijpulidos — APPROVED** [review]
Looks good to me!

**Pull request merged**
