### PR TITLE
Check if dgl 2.3.0 works

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mattwthompson** [comment]
Presumably this would need to also have a release, too?

**Comment by mikemhenry** [comment]
If it JustWorks :tm: then I should be able to just bump the pin on the conda-forge repo. The unit tests ran fine on my last check, just python 3.9 failing b/c of amber tools, so it is likely we won't need a new release.

**Comment by mikemhenry** [comment]
And the other error is just versioneer needing and update which I can do in this PR (and is already fixed on conda-forge with a patch)

**Comment by mattwthompson** [comment]
I'll leave it all up to you, but if the 1.x pin in the current release was just precautionary (and major changes here aren't needed to work with 2.x) as seems to be the case here, great!

**Pull request merged**
