### PR TITLE
Update README.md Install Steps

### LINKED ISSUE #195: Issue with conda installation
Hi, 
I am experiencing problems in installing with 
`conda install -c conda-forge "espaloma=0.3.2"`
as suggested in the README.

Looks like conda gets stuck in solving the environment (more than a day).
`Solving environment: | `

I tried on 3 different machines and also with different python versions (3.6, 3.7, 3.8, 3.9).

Do you have any suggestion - suggested python version etc.?

### PR DESCRIPTION
**Pull request by mikemhenry**
Fixes #195

### CODE REVIEW

**Comment by mattwthompson** [comment]
Purely out of curiosity, how far away is Espaloma from running natively on Apple Silicon? I assume it's a few of the dependencies

**Comment by mikemhenry** [comment]
We did get DGL cross compiled, so other deps might need work but soon :tm:

**Review by ijpulidos — APPROVED** [review]
LGTM!

**Comment by mikemhenry** [comment]
Might need to drop the osx subdir trick if dlg 2 works ref #220

**Comment by mikemhenry** [comment]
This is true today, but will need to be update with the next espaloma release

**Pull request merged**
