### PR TITLE
Update versioneer

### PR DESCRIPTION
**Pull request by mattwthompson**
```shell
$ pip install versioneer
$ versioneer install
```

magic and then everything works in Python 3.12 (surely)

### CODE REVIEW

**Comment by mattwthompson** [comment]
Aha .... but of course
```
    The following packages are incompatible
      ├─ dgl 1.1.2**  is installable with the potential options
      │  ├─ dgl 1.1.2 would require
      │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
      │  ├─ dgl 1.1.2 would require
      │  │  └─ python_abi 3.11.* *_cp311, which can be installed;
      │  └─ dgl 1.1.2 would require
      │     └─ python_abi 3.9.* *_cp39, which can be installed;
      └─ python 3.12**  is not installable because there are no viable options
         ├─ python 3.12.0 would require
         │  └─ python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported;
         └─ python 3.12.0rc3 would require
            └─ _python_rc, which does not exist (perhaps a missing channel).

**Comment by mikemhenry** [comment]
I've been going around updating versioneer as run into problems with it, have you played with the non-vendored method at all? It is "new" but seems more robust than manually having to update

**Comment by mattwthompson** [comment]
I haven't done that myself - if anything I've seen people move to different solutions altogether, I think MDAnalysis uses https://pypi.org/project/versioningit/

For this PR, would you prefer

1. Drop the 3.12 tests for now, trust the automation, and just hope stuff builds downstream
2. Wait until `conda-forge/dgl` has 3.12 builds (?)
3. Pull down DGL from another source (`dglteam`? PyPI?)
4. Other options?

**Comment by mikemhenry** [comment]
done in #220

**Pull request closed without merging**
